#UM SIMPLES TESTE DE SOMA EM PYTHON PARA PODER SER EXECUTADO NO CMD/


#DIGITANDO DOIS VALORES DE ENTRADA
N1 = float(input("DIGITE UM NUMERO = "))
N2 = float(input("DIGITE UM NUMERO = "))
#SOMANDO ESTES VALORES DE ENTRADA
soma = N1 + N2
#MOSTRNDO OS VALORES SOMADOS E O RESULTADO DA SOMA 
print(f"A SOMA DE {N1} COM {N2} RESULTARA {soma}")
